id = "klog"
name = "klog"
version = "0.1.0"
schema_version = 1
authors = ["Quentin Robcis"]
description = "Support for the klog plain-text time-tracking format."
repository = "https://github.com/quentinrobcis/klog-zed"

[grammars.klog]
repository = "https://github.com/Ansimorph/tree-sitter-klog"
rev = "0b215fe75bdeb8368546e3cee36aca8c19212d06"

[language_servers.klog-lsp]
name = "klog-lsp"
languages = ["klog"]
